version: '3.4'

services:
  streamlit:
    image: streamlit
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 10090"]
    ports:
      - 10090:10090
      - 5678:5678
    environment:
      - FLASK_APP=app\app.py
